import type { StoredIngredient } from "@workspace/db";

/**
 * Curated library of real supplement ingredients with clinically-grounded
 * timing metadata. Used both as standalone products and as the ingredient
 * pool for generated blends (see productGenerator.ts).
 */
export const INGREDIENT_LIBRARY: StoredIngredient[] = [
  // --- Vitamins ---
  { name: "Vitamin A (retinyl palmitate)", mgAmount: 0.9, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin B1 (thiamine)", mgAmount: 1.2, timingWindow: "with_meal" },
  { name: "Vitamin B2 (riboflavin)", mgAmount: 1.3, timingWindow: "with_meal" },
  { name: "Vitamin B3 (niacin)", mgAmount: 16, timingWindow: "with_meal" },
  { name: "Vitamin B5 (pantothenic acid)", mgAmount: 5, timingWindow: "with_meal" },
  { name: "Vitamin B6", mgAmount: 5, timingWindow: "with_meal" },
  { name: "Vitamin B7 (biotin)", mgAmount: 0.3, timingWindow: "flexible" },
  { name: "Vitamin B9 (folate)", mgAmount: 0.4, timingWindow: "with_meal" },
  { name: "Vitamin B12 (methylcobalamin)", mgAmount: 0.5, timingWindow: "with_meal" },
  { name: "Vitamin B-complex", mgAmount: 50, timingWindow: "with_meal" },
  { name: "Vitamin C", mgAmount: 500, timingWindow: "with_meal", pairWith: "Iron bisglycinate" },
  { name: "Vitamin D3", mgAmount: 0.125, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin E (mixed tocopherols)", mgAmount: 15, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin K1", mgAmount: 0.09, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin K2 (MK-7)", mgAmount: 0.1, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Choline bitartrate", mgAmount: 250, timingWindow: "with_meal" },

  // --- Minerals ---
  { name: "Iron bisglycinate", mgAmount: 25, mineralClass: "iron", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Ferrous sulfate", mgAmount: 65, mineralClass: "iron", timingWindow: "empty_stomach", avoidNearMedicationHours: 4 },
  { name: "Zinc picolinate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Zinc gluconate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Magnesium glycinate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium citrate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium threonate", mgAmount: 144, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Calcium citrate", mgAmount: 250, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Calcium carbonate", mgAmount: 500, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Potassium citrate", mgAmount: 99, timingWindow: "with_meal" },
  { name: "Selenium (selenomethionine)", mgAmount: 0.055, timingWindow: "with_meal" },
  { name: "Iodine (potassium iodide)", mgAmount: 0.15, timingWindow: "with_meal" },
  { name: "Chromium picolinate", mgAmount: 0.2, timingWindow: "with_meal" },
  { name: "Manganese", mgAmount: 2, timingWindow: "with_meal" },
  { name: "Copper (glycinate)", mgAmount: 0.9, timingWindow: "with_meal" },
  { name: "Molybdenum", mgAmount: 0.045, timingWindow: "with_meal" },
  { name: "Boron", mgAmount: 3, timingWindow: "with_meal" },

  // --- Amino acids / performance ---
  { name: "L-theanine", mgAmount: 200, timingWindow: "flexible" },
  { name: "L-tyrosine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-carnitine tartrate", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-arginine", mgAmount: 3000, timingWindow: "empty_stomach" },
  { name: "L-citrulline malate", mgAmount: 6000, timingWindow: "empty_stomach" },
  { name: "Taurine", mgAmount: 1000, timingWindow: "flexible" },
  { name: "Glycine", mgAmount: 3000, timingWindow: "evening" },
  { name: "L-glutamine", mgAmount: 5000, timingWindow: "flexible" },
  { name: "L-lysine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Beta-alanine", mgAmount: 3200, timingWindow: "flexible" },
  { name: "Creatine monohydrate", mgAmount: 5000, timingWindow: "flexible" },
  { name: "Caffeine anhydrous", mgAmount: 200, timingWindow: "flexible" },
  { name: "HMB", mgAmount: 3000, timingWindow: "with_meal" },
  { name: "Whey protein isolate", mgAmount: 25000, timingWindow: "flexible" },
  { name: "BCAA 2:1:1", mgAmount: 5000, timingWindow: "flexible" },
  { name: "Betaine anhydrous (TMG)", mgAmount: 2500, timingWindow: "with_meal" },

  // --- Herbs & adaptogens ---
  { name: "Ashwagandha (KSM-66)", mgAmount: 300, timingWindow: "evening" },
  { name: "Rhodiola rosea", mgAmount: 250, timingWindow: "evening" },
  { name: "Holy basil (tulsi)", mgAmount: 150, timingWindow: "with_meal" },
  { name: "Panax ginseng", mgAmount: 200, timingWindow: "with_meal" },
  { name: "Maca root", mgAmount: 1500, timingWindow: "with_meal" },
  { name: "Turmeric (curcumin)", mgAmount: 500, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Ginger root extract", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Milk thistle (silymarin)", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Echinacea purpurea", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Elderberry extract", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Garlic extract (allicin)", mgAmount: 600, timingWindow: "with_meal" },
  { name: "Green tea extract (EGCG)", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Guarana extract", mgAmount: 200, timingWindow: "flexible" },
  { name: "Yerba mate extract", mgAmount: 200, timingWindow: "flexible" },
  { name: "Valerian root", mgAmount: 400, timingWindow: "evening" },
  { name: "Chamomile extract", mgAmount: 300, timingWindow: "evening" },
  { name: "Passionflower extract", mgAmount: 250, timingWindow: "evening" },
  { name: "Lemon balm extract", mgAmount: 300, timingWindow: "evening" },
  { name: "Hops extract", mgAmount: 150, timingWindow: "evening" },
  { name: "Bacopa monnieri", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Ginkgo biloba", mgAmount: 120, timingWindow: "with_meal" },
  { name: "Lion's mane mushroom", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Reishi mushroom", mgAmount: 500, timingWindow: "evening" },
  { name: "Cordyceps mushroom", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Chaga mushroom", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Astragalus root", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Schisandra berry", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Eleuthero (Siberian ginseng)", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Magnolia bark extract", mgAmount: 200, timingWindow: "evening" },
  { name: "Relora", mgAmount: 250, timingWindow: "evening" },
  { name: "Phosphatidylserine", mgAmount: 100, fatSoluble: true, timingWindow: "evening" },
  { name: "GABA", mgAmount: 250, timingWindow: "evening" },
  { name: "5-HTP", mgAmount: 100, timingWindow: "evening" },
  { name: "Melatonin", mgAmount: 3, timingWindow: "evening" },
  { name: "NAC (N-acetylcysteine)", mgAmount: 600, timingWindow: "empty_stomach" },
  { name: "Maral root", mgAmount: 300, timingWindow: "evening" },
  { name: "Kava root extract", mgAmount: 250, timingWindow: "evening" },
  { name: "St. John's wort", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Fenugreek seed extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Tribulus terrestris", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Saw palmetto extract", mgAmount: 320, fatSoluble: true, timingWindow: "with_meal" },
  { name: "DIM (diindolylmethane)", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Chasteberry (vitex)", mgAmount: 400, timingWindow: "with_meal" },
  { name: "DHEA", mgAmount: 25, timingWindow: "with_meal" },

  // --- Fats / omega ---
  { name: "Omega-3 (EPA/DHA)", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Krill oil", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Algae oil (vegan DHA)", mgAmount: 500, fatSoluble: true, timingWindow: "with_meal" },
  { name: "CLA (conjugated linoleic acid)", mgAmount: 3000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Evening primrose oil", mgAmount: 1300, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Borage oil (GLA)", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Flaxseed oil", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },

  // --- Probiotics / digestive ---
  { name: "Multi-strain probiotic", mgAmount: 50, timingWindow: "empty_stomach" },
  { name: "Lactobacillus acidophilus", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Bifidobacterium lactis", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Digestive enzyme blend", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Betaine HCl", mgAmount: 650, timingWindow: "with_meal" },
  { name: "Psyllium husk", mgAmount: 5000, timingWindow: "empty_stomach" },
  { name: "Inulin (prebiotic fiber)", mgAmount: 3000, timingWindow: "flexible" },

  // --- Joint / bone / skin ---
  { name: "Glucosamine sulfate", mgAmount: 1500, timingWindow: "with_meal" },
  { name: "Chondroitin sulfate", mgAmount: 1200, timingWindow: "with_meal" },
  { name: "MSM (methylsulfonylmethane)", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Collagen peptides", mgAmount: 10000, timingWindow: "flexible" },
  { name: "Hyaluronic acid", mgAmount: 120, timingWindow: "with_meal" },
  { name: "Boswellia serrata extract", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Silica (bamboo extract)", mgAmount: 100, timingWindow: "with_meal" },

  // --- Cognitive ---
  { name: "Alpha-GPC", mgAmount: 300, timingWindow: "empty_stomach" },
  { name: "Huperzine A", mgAmount: 0.05, timingWindow: "empty_stomach" },
  { name: "CDP-choline (citicoline)", mgAmount: 250, timingWindow: "with_meal" },
  { name: "DMAE", mgAmount: 150, timingWindow: "empty_stomach" },
  { name: "PQQ", mgAmount: 20, timingWindow: "with_meal" },

  // --- Heart / metabolic ---
  { name: "CoQ10 (ubiquinone)", mgAmount: 100, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Ubiquinol", mgAmount: 100, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Red yeast rice", mgAmount: 1200, timingWindow: "evening" },
  { name: "Niacin (flush-free)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Alpha lipoic acid", mgAmount: 300, timingWindow: "empty_stomach" },
  { name: "Berberine", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Resveratrol", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Quercetin", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Apigenin", mgAmount: 50, timingWindow: "evening" },
  { name: "Luteolin", mgAmount: 100, timingWindow: "evening" },
  { name: "Fisetin", mgAmount: 100, fatSoluble: true, timingWindow: "with_meal" },
  { name: "L-tryptophan", mgAmount: 500, timingWindow: "evening" },
  { name: "Honokiol", mgAmount: 250, timingWindow: "evening" },
  { name: "NMN (nicotinamide mononucleotide)", mgAmount: 250, timingWindow: "empty_stomach" },
  { name: "NR (nicotinamide riboside)", mgAmount: 300, timingWindow: "empty_stomach" },

  // --- Eye health ---
  { name: "Lutein", mgAmount: 20, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Zeaxanthin", mgAmount: 4, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Bilberry extract", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Astaxanthin", mgAmount: 6, fatSoluble: true, timingWindow: "with_meal" },

  // --- Misc / superfoods ---
  { name: "Spirulina", mgAmount: 3000, timingWindow: "with_meal" },
  { name: "Chlorella", mgAmount: 3000, timingWindow: "with_meal" },
  { name: "Apple cider vinegar (dried)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "D-mannose", mgAmount: 1000, timingWindow: "empty_stomach" },
  { name: "Cranberry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Beta glucan", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Probiotic 50B", mgAmount: 50, timingWindow: "empty_stomach" },

  // --- More vitamins / active cofactors ---
  { name: "Vitamin D2 (ergocalciferol)", mgAmount: 0.125, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Methylfolate (5-MTHF)", mgAmount: 0.4, timingWindow: "with_meal" },
  { name: "Pyridoxal-5-phosphate (P5P)", mgAmount: 5, timingWindow: "with_meal" },
  { name: "Riboflavin-5-phosphate", mgAmount: 1.3, timingWindow: "with_meal" },
  { name: "Folinic acid", mgAmount: 0.4, timingWindow: "with_meal" },
  { name: "Inositol", mgAmount: 2000, timingWindow: "flexible" },
  { name: "PABA (para-aminobenzoic acid)", mgAmount: 50, timingWindow: "with_meal" },
  { name: "Beta-carotene", mgAmount: 5, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Lycopene", mgAmount: 10, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Choline CDP (citicoline)", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Phosphatidylcholine", mgAmount: 420, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Lecithin (soy)", mgAmount: 1200, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Sunflower lecithin", mgAmount: 1200, fatSoluble: true, timingWindow: "with_meal" },

  // --- More minerals ---
  { name: "Zinc orotate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Zinc citrate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Magnesium malate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium oxide", mgAmount: 400, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium taurate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Iron polysaccharide complex", mgAmount: 25, mineralClass: "iron", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Calcium hydroxyapatite", mgAmount: 500, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Potassium gluconate", mgAmount: 99, timingWindow: "with_meal" },
  { name: "Chromium GTF", mgAmount: 0.2, timingWindow: "with_meal" },
  { name: "Vanadium (vanadyl sulfate)", mgAmount: 0.1, timingWindow: "with_meal" },
  { name: "Lithium orotate", mgAmount: 5, timingWindow: "evening" },
  { name: "Strontium citrate", mgAmount: 680, timingWindow: "evening" },
  { name: "Silicon (orthosilicic acid)", mgAmount: 10, timingWindow: "with_meal" },

  // --- More amino acids / recovery ---
  { name: "L-ornithine", mgAmount: 500, timingWindow: "evening" },
  { name: "L-cysteine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-methionine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-histidine", mgAmount: 500, timingWindow: "with_meal" },
  { name: "N-acetyl L-tyrosine (NALT)", mgAmount: 350, timingWindow: "empty_stomach" },
  { name: "L-carnosine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Agmatine sulfate", mgAmount: 750, timingWindow: "empty_stomach" },
  { name: "Nitrosigine", mgAmount: 1500, timingWindow: "empty_stomach" },
  { name: "Arginine alpha-ketoglutarate (AAKG)", mgAmount: 3000, timingWindow: "empty_stomach" },
  { name: "SAM-e (S-adenosylmethionine)", mgAmount: 400, timingWindow: "empty_stomach" },

  // --- Hormonal / longevity ---
  { name: "7-Keto DHEA", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Pregnenolone", mgAmount: 50, timingWindow: "with_meal" },
  { name: "R-lipoic acid", mgAmount: 300, timingWindow: "empty_stomach" },
  { name: "Glutathione (reduced)", mgAmount: 250, timingWindow: "empty_stomach" },
  { name: "Mucuna pruriens (L-DOPA)", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Tongkat Ali (longjack)", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Horny goat weed (epimedium)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Yohimbine HCl", mgAmount: 5, timingWindow: "empty_stomach" },
  { name: "Damiana leaf extract", mgAmount: 400, timingWindow: "evening" },
  { name: "Muira puama extract", mgAmount: 500, timingWindow: "with_meal" },

  // --- More herbs & extracts (nootropic/mood/immune/circulatory) ---
  { name: "Saffron extract (Crocus sativus)", mgAmount: 30, timingWindow: "with_meal" },
  { name: "Kanna extract (Sceletium tortuosum)", mgAmount: 25, timingWindow: "flexible" },
  { name: "American ginseng", mgAmount: 200, timingWindow: "with_meal" },
  { name: "Andrographis extract", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Olive leaf extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Oregano oil", mgAmount: 150, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Cat's claw extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Pau d'arco extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Slippery elm bark", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Marshmallow root extract", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Licorice root (DGL)", mgAmount: 400, timingWindow: "empty_stomach" },
  { name: "Aloe vera extract", mgAmount: 200, timingWindow: "empty_stomach" },
  { name: "Wheatgrass powder", mgAmount: 3000, timingWindow: "empty_stomach" },
  { name: "Barley grass powder", mgAmount: 3000, timingWindow: "empty_stomach" },
  { name: "Moringa leaf extract", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Ashitaba extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Noni fruit extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Goji berry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Acai berry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Camu camu extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Baobab fruit powder", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Pomegranate extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Black currant extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Grape seed extract", mgAmount: 150, timingWindow: "with_meal" },
  { name: "Pine bark extract (Pycnogenol)", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Hawthorn berry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Beet root extract", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Cinnamon bark extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Black cohosh extract", mgAmount: 40, timingWindow: "with_meal" },
  { name: "Red clover extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Dong quai extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Black seed oil (Nigella sativa)", mgAmount: 500, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Sea buckthorn oil", mgAmount: 500, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Hemp seed oil", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "MCT oil powder", mgAmount: 5000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Maitake mushroom extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Shiitake mushroom extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Turkey tail mushroom extract", mgAmount: 500, timingWindow: "with_meal" },

  // --- Additional mineral forms ---
  { name: "Magnesium aspartate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium chloride", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium orotate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium l-lactate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Zinc acetate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Zinc sulfate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Zinc monomethionine (OptiZinc)", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Zinc bisglycinate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Calcium lactate", mgAmount: 250, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Calcium gluconate", mgAmount: 250, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Calcium malate", mgAmount: 250, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Ferrous fumarate", mgAmount: 65, mineralClass: "iron", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Ferrous gluconate", mgAmount: 35, mineralClass: "iron", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Carbonyl iron", mgAmount: 45, mineralClass: "iron", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Heme iron polypeptide", mgAmount: 12, mineralClass: "iron", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Potassium chloride", mgAmount: 99, timingWindow: "with_meal" },
  { name: "Potassium bicarbonate", mgAmount: 99, timingWindow: "with_meal" },
  { name: "Selenium (sodium selenite)", mgAmount: 0.055, timingWindow: "with_meal" },
  { name: "Selenium yeast", mgAmount: 0.2, timingWindow: "with_meal" },
  { name: "Copper bisglycinate", mgAmount: 2, timingWindow: "with_meal" },
  { name: "Manganese citrate", mgAmount: 2, timingWindow: "with_meal" },
  { name: "Chromium nicotinate", mgAmount: 0.2, timingWindow: "with_meal" },
  { name: "Molybdenum glycinate", mgAmount: 0.075, timingWindow: "with_meal" },
  { name: "Iodine (kelp)", mgAmount: 0.15, timingWindow: "with_meal" },
  { name: "Lugol's iodine", mgAmount: 0.15, timingWindow: "with_meal" },
  { name: "Trace mineral complex", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Electrolyte blend", mgAmount: 1000, timingWindow: "flexible" },
  { name: "Sodium bicarbonate", mgAmount: 3000, timingWindow: "empty_stomach" },
  { name: "Coral calcium", mgAmount: 500, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Phosphorus (as phosphate)", mgAmount: 250, timingWindow: "with_meal" },

  // --- Additional vitamins / cofactors ---
  { name: "Vitamin A (retinyl acetate)", mgAmount: 0.9, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Mixed carotenoids", mgAmount: 6, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin C (sodium ascorbate)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Vitamin C (calcium ascorbate)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Liposomal vitamin C", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Acerola cherry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Vitamin E (tocotrienols)", mgAmount: 50, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin K2 (MK-4)", mgAmount: 1.5, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Benfotiamine", mgAmount: 150, timingWindow: "with_meal" },
  { name: "Niacinamide", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Adenosylcobalamin", mgAmount: 0.5, timingWindow: "with_meal" },
  { name: "Hydroxocobalamin", mgAmount: 0.5, timingWindow: "with_meal" },
  { name: "Cyanocobalamin", mgAmount: 0.5, timingWindow: "with_meal" },
  { name: "Dexpanthenol (provitamin B5)", mgAmount: 5, timingWindow: "with_meal" },
  { name: "D-chiro-inositol", mgAmount: 600, timingWindow: "flexible" },

  // --- Additional amino acids / performance ---
  { name: "L-proline", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-serine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-threonine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-valine", mgAmount: 1000, timingWindow: "flexible" },
  { name: "L-leucine", mgAmount: 2500, timingWindow: "flexible" },
  { name: "L-isoleucine", mgAmount: 1000, timingWindow: "flexible" },
  { name: "L-aspartic acid", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-glutamic acid", mgAmount: 500, timingWindow: "with_meal" },
  { name: "L-phenylalanine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "DL-phenylalanine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-alanine", mgAmount: 500, timingWindow: "flexible" },
  { name: "Dimethylglycine (DMG)", mgAmount: 125, timingWindow: "with_meal" },
  { name: "Acetyl-L-carnitine (ALCAR)", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Propionyl-L-carnitine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-carnitine fumarate", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Creatine HCl", mgAmount: 750, timingWindow: "flexible" },
  { name: "Kre-Alkalyn (buffered creatine)", mgAmount: 1500, timingWindow: "flexible" },
  { name: "Creatine nitrate", mgAmount: 1000, timingWindow: "flexible" },
  { name: "Beta-hydroxybutyrate (BHB)", mgAmount: 10000, timingWindow: "flexible" },
  { name: "D-ribose", mgAmount: 5000, timingWindow: "flexible" },
  { name: "Glycerol powder (HydroMax)", mgAmount: 2000, timingWindow: "empty_stomach" },
  { name: "L-norvaline", mgAmount: 300, timingWindow: "empty_stomach" },
  { name: "PEAK ATP (adenosine triphosphate)", mgAmount: 400, timingWindow: "empty_stomach" },
  { name: "Theacrine", mgAmount: 100, timingWindow: "flexible" },
  { name: "Dynamine (methylliberine)", mgAmount: 100, timingWindow: "flexible" },

  // --- Additional nootropics / cognitive ---
  { name: "Sulbutiamine", mgAmount: 400, timingWindow: "empty_stomach" },
  { name: "Noopept", mgAmount: 15, timingWindow: "empty_stomach" },
  { name: "Piracetam", mgAmount: 800, timingWindow: "empty_stomach" },
  { name: "Aniracetam", mgAmount: 750, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Oxiracetam", mgAmount: 800, timingWindow: "empty_stomach" },
  { name: "Phenylpiracetam", mgAmount: 100, timingWindow: "empty_stomach" },
  { name: "Vinpocetine", mgAmount: 10, timingWindow: "with_meal" },
  { name: "Centrophenoxine", mgAmount: 250, timingWindow: "empty_stomach" },
  { name: "Pterostilbene", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Uridine monophosphate", mgAmount: 250, timingWindow: "flexible" },
  { name: "Gotu kola (Centella asiatica)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Polygala tenuifolia", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Celastrus paniculatus", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Theobromine", mgAmount: 100, timingWindow: "flexible" },

  // --- Additional herbs & extracts ---
  { name: "Shilajit", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Gynostemma (jiaogulan)", mgAmount: 450, timingWindow: "with_meal" },
  { name: "He shou wu (Fo-ti)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Cistanche extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Pine pollen", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Stinging nettle root", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Horse chestnut extract", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Butcher's broom extract", mgAmount: 200, timingWindow: "with_meal" },
  { name: "Gymnema sylvestre", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Bitter melon extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Banaba leaf extract", mgAmount: 48, timingWindow: "with_meal" },
  { name: "Bitter orange (synephrine)", mgAmount: 50, timingWindow: "empty_stomach" },
  { name: "Green coffee bean extract", mgAmount: 400, timingWindow: "empty_stomach" },
  { name: "Garcinia cambogia (HCA)", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Forskolin (Coleus forskohlii)", mgAmount: 250, timingWindow: "empty_stomach" },
  { name: "Raspberry ketones", mgAmount: 200, timingWindow: "with_meal" },
  { name: "African mango (Irvingia)", mgAmount: 150, timingWindow: "with_meal" },
  { name: "White kidney bean extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Guggul extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Triphala", mgAmount: 1000, timingWindow: "evening" },
  { name: "Amla (Indian gooseberry)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Neem extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Shatavari root", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Tinospora (Guduchi)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Arjuna bark extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Kudzu root extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Skullcap extract", mgAmount: 400, timingWindow: "evening" },
  { name: "California poppy extract", mgAmount: 400, timingWindow: "evening" },
  { name: "Ashwagandha (Sensoril)", mgAmount: 250, timingWindow: "evening" },
  { name: "Cordyceps militaris", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Wormwood extract", mgAmount: 200, timingWindow: "with_meal" },
  { name: "Clove extract", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Goldenseal root", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Oregon grape root", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Barberry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Burdock root extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Dandelion root extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Red raspberry leaf", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Feverfew extract", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Butterbur extract", mgAmount: 75, timingWindow: "with_meal" },
  { name: "White willow bark", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Devil's claw extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Suma root", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Ziziphus (jujube seed)", mgAmount: 500, timingWindow: "evening" },
  { name: "Tart cherry extract", mgAmount: 480, timingWindow: "evening" },
  { name: "Fadogia agrestis", mgAmount: 600, timingWindow: "with_meal" },
  { name: "Bladderwrack", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Kelp extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Fennel seed extract", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Artichoke leaf extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Peppermint oil (enteric)", mgAmount: 180, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Bergamot extract (citrus bergamot)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Policosanol", mgAmount: 10, timingWindow: "evening" },
  { name: "Cocoa flavanols", mgAmount: 500, timingWindow: "flexible" },
  { name: "Capsaicin (cayenne extract)", mgAmount: 50, timingWindow: "with_meal" },
  { name: "Grains of paradise extract", mgAmount: 40, timingWindow: "with_meal" },

  // --- Additional antioxidants / flavonoids ---
  { name: "Sulforaphane (broccoli extract)", mgAmount: 50, timingWindow: "with_meal" },
  { name: "Ellagic acid", mgAmount: 200, timingWindow: "with_meal" },
  { name: "Hesperidin", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Rutin", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Diosmin", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Naringin", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Fucoxanthin", mgAmount: 5, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Ergothioneine", mgAmount: 5, timingWindow: "with_meal" },
  { name: "Spermidine (wheat germ extract)", mgAmount: 1, timingWindow: "flexible" },
  { name: "SOD (superoxide dismutase)", mgAmount: 250, timingWindow: "empty_stomach" },
  { name: "Liposomal glutathione", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Molecular hydrogen tablets", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Urolithin A", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Calcium alpha-ketoglutarate", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Alpha-ketoglutarate (AKG)", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Beta-sitosterol", mgAmount: 400, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Plant sterols/stanols", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Chrysin", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Calcium D-glucarate", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Indole-3-carbinol (I3C)", mgAmount: 200, timingWindow: "with_meal" },

  // --- Digestive enzymes / probiotics / fiber ---
  { name: "Bromelain", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Papain", mgAmount: 200, timingWindow: "empty_stomach" },
  { name: "Serrapeptase", mgAmount: 40, timingWindow: "empty_stomach" },
  { name: "Nattokinase", mgAmount: 100, timingWindow: "empty_stomach" },
  { name: "Lipase", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Amylase", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Protease", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Lactase", mgAmount: 50, timingWindow: "with_meal" },
  { name: "Ox bile extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Pancreatin", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Saccharomyces boulardii", mgAmount: 250, timingWindow: "empty_stomach" },
  { name: "Bifidobacterium longum", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Bifidobacterium bifidum", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Lactobacillus rhamnosus", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Lactobacillus plantarum", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Lactobacillus reuteri", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Bacillus coagulans", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Bacillus subtilis", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "FOS (fructooligosaccharides)", mgAmount: 3000, timingWindow: "flexible" },
  { name: "GOS (galactooligosaccharides)", mgAmount: 3000, timingWindow: "flexible" },
  { name: "Acacia fiber", mgAmount: 5000, timingWindow: "flexible" },
  { name: "Glucomannan (konjac)", mgAmount: 1000, timingWindow: "empty_stomach" },
  { name: "Apple pectin", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Activated charcoal", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Bentonite clay", mgAmount: 1000, timingWindow: "empty_stomach" },
  { name: "Zinc carnosine", mgAmount: 75, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },

  // --- Joint / skin / structural / misc ---
  { name: "Glucosamine HCl", mgAmount: 1500, timingWindow: "with_meal" },
  { name: "Type II collagen (UC-II)", mgAmount: 40, timingWindow: "empty_stomach" },
  { name: "Marine collagen", mgAmount: 10000, timingWindow: "flexible" },
  { name: "Eggshell membrane (NEM)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Cetyl myristoleate (CMO)", mgAmount: 500, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Phytoceramides", mgAmount: 350, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Horsetail extract", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Larch arabinogalactan", mgAmount: 1500, timingWindow: "flexible" },
  { name: "Bovine colostrum", mgAmount: 1000, timingWindow: "empty_stomach" },
  { name: "Lactoferrin", mgAmount: 250, timingWindow: "empty_stomach" },
  { name: "Oat beta-glucan", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Nettle leaf extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Sea moss (Irish moss)", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Black elderflower extract", mgAmount: 300, timingWindow: "with_meal" },
];

export const INGREDIENT_BY_NAME = new Map(INGREDIENT_LIBRARY.map((i) => [i.name, i]));
