import type { StoredIngredient } from "@workspace/db";

/**
 * Curated library of real supplement ingredients with clinically-grounded
 * timing metadata. Used both as standalone products and as the ingredient
 * pool for generated blends (see productGenerator.ts).
 */
export const INGREDIENT_LIBRARY: StoredIngredient[] = [
  // --- Vitamins ---
  { name: "Vitamin A (retinyl palmitate)", mgAmount: 0.9, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin B1 (thiamine)", mgAmount: 1.2, timingWindow: "with_meal" },
  { name: "Vitamin B2 (riboflavin)", mgAmount: 1.3, timingWindow: "with_meal" },
  { name: "Vitamin B3 (niacin)", mgAmount: 16, timingWindow: "with_meal" },
  { name: "Vitamin B5 (pantothenic acid)", mgAmount: 5, timingWindow: "with_meal" },
  { name: "Vitamin B6", mgAmount: 5, timingWindow: "with_meal" },
  { name: "Vitamin B7 (biotin)", mgAmount: 0.3, timingWindow: "flexible" },
  { name: "Vitamin B9 (folate)", mgAmount: 0.4, timingWindow: "with_meal" },
  { name: "Vitamin B12 (methylcobalamin)", mgAmount: 0.5, timingWindow: "with_meal" },
  { name: "Vitamin B-complex", mgAmount: 50, timingWindow: "with_meal" },
  { name: "Vitamin C", mgAmount: 500, timingWindow: "with_meal", pairWith: "Iron bisglycinate" },
  { name: "Vitamin D3", mgAmount: 0.125, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin E (mixed tocopherols)", mgAmount: 15, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin K1", mgAmount: 0.09, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Vitamin K2 (MK-7)", mgAmount: 0.1, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Choline bitartrate", mgAmount: 250, timingWindow: "with_meal" },

  // --- Minerals ---
  { name: "Iron bisglycinate", mgAmount: 25, mineralClass: "iron", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Ferrous sulfate", mgAmount: 65, mineralClass: "iron", timingWindow: "empty_stomach", avoidNearMedicationHours: 4 },
  { name: "Zinc picolinate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Zinc gluconate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Magnesium glycinate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium citrate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium threonate", mgAmount: 144, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Calcium citrate", mgAmount: 250, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Calcium carbonate", mgAmount: 500, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Potassium citrate", mgAmount: 99, timingWindow: "with_meal" },
  { name: "Selenium (selenomethionine)", mgAmount: 0.055, timingWindow: "with_meal" },
  { name: "Iodine (potassium iodide)", mgAmount: 0.15, timingWindow: "with_meal" },
  { name: "Chromium picolinate", mgAmount: 0.2, timingWindow: "with_meal" },
  { name: "Manganese", mgAmount: 2, timingWindow: "with_meal" },
  { name: "Copper (glycinate)", mgAmount: 0.9, timingWindow: "with_meal" },
  { name: "Molybdenum", mgAmount: 0.045, timingWindow: "with_meal" },
  { name: "Boron", mgAmount: 3, timingWindow: "with_meal" },

  // --- Amino acids / performance ---
  { name: "L-theanine", mgAmount: 200, timingWindow: "flexible" },
  { name: "L-tyrosine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-carnitine tartrate", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-arginine", mgAmount: 3000, timingWindow: "empty_stomach" },
  { name: "L-citrulline malate", mgAmount: 6000, timingWindow: "empty_stomach" },
  { name: "Taurine", mgAmount: 1000, timingWindow: "flexible" },
  { name: "Glycine", mgAmount: 3000, timingWindow: "evening" },
  { name: "L-glutamine", mgAmount: 5000, timingWindow: "flexible" },
  { name: "L-lysine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Beta-alanine", mgAmount: 3200, timingWindow: "flexible" },
  { name: "Creatine monohydrate", mgAmount: 5000, timingWindow: "flexible" },
  { name: "Caffeine anhydrous", mgAmount: 200, timingWindow: "flexible" },
  { name: "HMB", mgAmount: 3000, timingWindow: "with_meal" },
  { name: "Whey protein isolate", mgAmount: 25000, timingWindow: "flexible" },
  { name: "BCAA 2:1:1", mgAmount: 5000, timingWindow: "flexible" },
  { name: "Betaine anhydrous (TMG)", mgAmount: 2500, timingWindow: "with_meal" },

  // --- Herbs & adaptogens ---
  { name: "Ashwagandha (KSM-66)", mgAmount: 300, timingWindow: "evening" },
  { name: "Rhodiola rosea", mgAmount: 250, timingWindow: "evening" },
  { name: "Holy basil (tulsi)", mgAmount: 150, timingWindow: "with_meal" },
  { name: "Panax ginseng", mgAmount: 200, timingWindow: "with_meal" },
  { name: "Maca root", mgAmount: 1500, timingWindow: "with_meal" },
  { name: "Turmeric (curcumin)", mgAmount: 500, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Ginger root extract", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Milk thistle (silymarin)", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Echinacea purpurea", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Elderberry extract", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Garlic extract (allicin)", mgAmount: 600, timingWindow: "with_meal" },
  { name: "Green tea extract (EGCG)", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Guarana extract", mgAmount: 200, timingWindow: "flexible" },
  { name: "Yerba mate extract", mgAmount: 200, timingWindow: "flexible" },
  { name: "Valerian root", mgAmount: 400, timingWindow: "evening" },
  { name: "Chamomile extract", mgAmount: 300, timingWindow: "evening" },
  { name: "Passionflower extract", mgAmount: 250, timingWindow: "evening" },
  { name: "Lemon balm extract", mgAmount: 300, timingWindow: "evening" },
  { name: "Hops extract", mgAmount: 150, timingWindow: "evening" },
  { name: "Bacopa monnieri", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Ginkgo biloba", mgAmount: 120, timingWindow: "with_meal" },
  { name: "Lion's mane mushroom", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Reishi mushroom", mgAmount: 500, timingWindow: "evening" },
  { name: "Cordyceps mushroom", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Chaga mushroom", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Astragalus root", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Schisandra berry", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Eleuthero (Siberian ginseng)", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Magnolia bark extract", mgAmount: 200, timingWindow: "evening" },
  { name: "Relora", mgAmount: 250, timingWindow: "evening" },
  { name: "Phosphatidylserine", mgAmount: 100, fatSoluble: true, timingWindow: "evening" },
  { name: "GABA", mgAmount: 250, timingWindow: "evening" },
  { name: "5-HTP", mgAmount: 100, timingWindow: "evening" },
  { name: "Melatonin", mgAmount: 3, timingWindow: "evening" },
  { name: "NAC (N-acetylcysteine)", mgAmount: 600, timingWindow: "empty_stomach" },
  { name: "Maral root", mgAmount: 300, timingWindow: "evening" },
  { name: "Kava root extract", mgAmount: 250, timingWindow: "evening" },
  { name: "St. John's wort", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Fenugreek seed extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Tribulus terrestris", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Saw palmetto extract", mgAmount: 320, fatSoluble: true, timingWindow: "with_meal" },
  { name: "DIM (diindolylmethane)", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Chasteberry (vitex)", mgAmount: 400, timingWindow: "with_meal" },
  { name: "DHEA", mgAmount: 25, timingWindow: "with_meal" },

  // --- Fats / omega ---
  { name: "Omega-3 (EPA/DHA)", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Krill oil", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Algae oil (vegan DHA)", mgAmount: 500, fatSoluble: true, timingWindow: "with_meal" },
  { name: "CLA (conjugated linoleic acid)", mgAmount: 3000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Evening primrose oil", mgAmount: 1300, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Borage oil (GLA)", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Flaxseed oil", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },

  // --- Probiotics / digestive ---
  { name: "Multi-strain probiotic", mgAmount: 50, timingWindow: "empty_stomach" },
  { name: "Lactobacillus acidophilus", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Bifidobacterium lactis", mgAmount: 10, timingWindow: "empty_stomach" },
  { name: "Digestive enzyme blend", mgAmount: 300, timingWindow: "with_meal" },
  { name: "Betaine HCl", mgAmount: 650, timingWindow: "with_meal" },
  { name: "Psyllium husk", mgAmount: 5000, timingWindow: "empty_stomach" },
  { name: "Inulin (prebiotic fiber)", mgAmount: 3000, timingWindow: "flexible" },

  // --- Joint / bone / skin ---
  { name: "Glucosamine sulfate", mgAmount: 1500, timingWindow: "with_meal" },
  { name: "Chondroitin sulfate", mgAmount: 1200, timingWindow: "with_meal" },
  { name: "MSM (methylsulfonylmethane)", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Collagen peptides", mgAmount: 10000, timingWindow: "flexible" },
  { name: "Hyaluronic acid", mgAmount: 120, timingWindow: "with_meal" },
  { name: "Boswellia serrata extract", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Silica (bamboo extract)", mgAmount: 100, timingWindow: "with_meal" },

  // --- Cognitive ---
  { name: "Alpha-GPC", mgAmount: 300, timingWindow: "empty_stomach" },
  { name: "Huperzine A", mgAmount: 0.05, timingWindow: "empty_stomach" },
  { name: "CDP-choline (citicoline)", mgAmount: 250, timingWindow: "with_meal" },
  { name: "DMAE", mgAmount: 150, timingWindow: "empty_stomach" },
  { name: "PQQ", mgAmount: 20, timingWindow: "with_meal" },

  // --- Heart / metabolic ---
  { name: "CoQ10 (ubiquinone)", mgAmount: 100, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Ubiquinol", mgAmount: 100, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Red yeast rice", mgAmount: 1200, timingWindow: "evening" },
  { name: "Niacin (flush-free)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Alpha lipoic acid", mgAmount: 300, timingWindow: "empty_stomach" },
  { name: "Berberine", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Resveratrol", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Quercetin", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Apigenin", mgAmount: 50, timingWindow: "evening" },
  { name: "Luteolin", mgAmount: 100, timingWindow: "evening" },
  { name: "Fisetin", mgAmount: 100, fatSoluble: true, timingWindow: "with_meal" },
  { name: "L-tryptophan", mgAmount: 500, timingWindow: "evening" },
  { name: "Honokiol", mgAmount: 250, timingWindow: "evening" },
  { name: "NMN (nicotinamide mononucleotide)", mgAmount: 250, timingWindow: "empty_stomach" },
  { name: "NR (nicotinamide riboside)", mgAmount: 300, timingWindow: "empty_stomach" },

  // --- Eye health ---
  { name: "Lutein", mgAmount: 20, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Zeaxanthin", mgAmount: 4, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Bilberry extract", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Astaxanthin", mgAmount: 6, fatSoluble: true, timingWindow: "with_meal" },

  // --- Misc / superfoods ---
  { name: "Spirulina", mgAmount: 3000, timingWindow: "with_meal" },
  { name: "Chlorella", mgAmount: 3000, timingWindow: "with_meal" },
  { name: "Apple cider vinegar (dried)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "D-mannose", mgAmount: 1000, timingWindow: "empty_stomach" },
  { name: "Cranberry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Beta glucan", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Probiotic 50B", mgAmount: 50, timingWindow: "empty_stomach" },

  // --- More vitamins / active cofactors ---
  { name: "Vitamin D2 (ergocalciferol)", mgAmount: 0.125, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Methylfolate (5-MTHF)", mgAmount: 0.4, timingWindow: "with_meal" },
  { name: "Pyridoxal-5-phosphate (P5P)", mgAmount: 5, timingWindow: "with_meal" },
  { name: "Riboflavin-5-phosphate", mgAmount: 1.3, timingWindow: "with_meal" },
  { name: "Folinic acid", mgAmount: 0.4, timingWindow: "with_meal" },
  { name: "Inositol", mgAmount: 2000, timingWindow: "flexible" },
  { name: "PABA (para-aminobenzoic acid)", mgAmount: 50, timingWindow: "with_meal" },
  { name: "Beta-carotene", mgAmount: 5, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Lycopene", mgAmount: 10, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Choline CDP (citicoline)", mgAmount: 250, timingWindow: "with_meal" },
  { name: "Phosphatidylcholine", mgAmount: 420, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Lecithin (soy)", mgAmount: 1200, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Sunflower lecithin", mgAmount: 1200, fatSoluble: true, timingWindow: "with_meal" },

  // --- More minerals ---
  { name: "Zinc orotate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Zinc citrate", mgAmount: 15, mineralClass: "zinc", timingWindow: "with_meal", avoidNearMedicationHours: 2 },
  { name: "Magnesium malate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium oxide", mgAmount: 400, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Magnesium taurate", mgAmount: 200, mineralClass: "magnesium", timingWindow: "evening" },
  { name: "Iron polysaccharide complex", mgAmount: 25, mineralClass: "iron", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Calcium hydroxyapatite", mgAmount: 500, mineralClass: "calcium", timingWindow: "with_meal", avoidNearMedicationHours: 4 },
  { name: "Potassium gluconate", mgAmount: 99, timingWindow: "with_meal" },
  { name: "Chromium GTF", mgAmount: 0.2, timingWindow: "with_meal" },
  { name: "Vanadium (vanadyl sulfate)", mgAmount: 0.1, timingWindow: "with_meal" },
  { name: "Lithium orotate", mgAmount: 5, timingWindow: "evening" },
  { name: "Strontium citrate", mgAmount: 680, timingWindow: "evening" },
  { name: "Silicon (orthosilicic acid)", mgAmount: 10, timingWindow: "with_meal" },

  // --- More amino acids / recovery ---
  { name: "L-ornithine", mgAmount: 500, timingWindow: "evening" },
  { name: "L-cysteine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-methionine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "L-histidine", mgAmount: 500, timingWindow: "with_meal" },
  { name: "N-acetyl L-tyrosine (NALT)", mgAmount: 350, timingWindow: "empty_stomach" },
  { name: "L-carnosine", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Agmatine sulfate", mgAmount: 750, timingWindow: "empty_stomach" },
  { name: "Nitrosigine", mgAmount: 1500, timingWindow: "empty_stomach" },
  { name: "Arginine alpha-ketoglutarate (AAKG)", mgAmount: 3000, timingWindow: "empty_stomach" },
  { name: "SAM-e (S-adenosylmethionine)", mgAmount: 400, timingWindow: "empty_stomach" },

  // --- Hormonal / longevity ---
  { name: "7-Keto DHEA", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Pregnenolone", mgAmount: 50, timingWindow: "with_meal" },
  { name: "R-lipoic acid", mgAmount: 300, timingWindow: "empty_stomach" },
  { name: "Glutathione (reduced)", mgAmount: 250, timingWindow: "empty_stomach" },
  { name: "Mucuna pruriens (L-DOPA)", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Tongkat Ali (longjack)", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Horny goat weed (epimedium)", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Yohimbine HCl", mgAmount: 5, timingWindow: "empty_stomach" },
  { name: "Damiana leaf extract", mgAmount: 400, timingWindow: "evening" },
  { name: "Muira puama extract", mgAmount: 500, timingWindow: "with_meal" },

  // --- More herbs & extracts (nootropic/mood/immune/circulatory) ---
  { name: "Saffron extract (Crocus sativus)", mgAmount: 30, timingWindow: "with_meal" },
  { name: "Kanna extract (Sceletium tortuosum)", mgAmount: 25, timingWindow: "flexible" },
  { name: "American ginseng", mgAmount: 200, timingWindow: "with_meal" },
  { name: "Andrographis extract", mgAmount: 400, timingWindow: "with_meal" },
  { name: "Olive leaf extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Oregano oil", mgAmount: 150, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Cat's claw extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Pau d'arco extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Slippery elm bark", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Marshmallow root extract", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Licorice root (DGL)", mgAmount: 400, timingWindow: "empty_stomach" },
  { name: "Aloe vera extract", mgAmount: 200, timingWindow: "empty_stomach" },
  { name: "Wheatgrass powder", mgAmount: 3000, timingWindow: "empty_stomach" },
  { name: "Barley grass powder", mgAmount: 3000, timingWindow: "empty_stomach" },
  { name: "Moringa leaf extract", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Ashitaba extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Noni fruit extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Goji berry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Acai berry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Camu camu extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Baobab fruit powder", mgAmount: 1000, timingWindow: "with_meal" },
  { name: "Pomegranate extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Black currant extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Grape seed extract", mgAmount: 150, timingWindow: "with_meal" },
  { name: "Pine bark extract (Pycnogenol)", mgAmount: 100, timingWindow: "with_meal" },
  { name: "Hawthorn berry extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Beet root extract", mgAmount: 500, timingWindow: "empty_stomach" },
  { name: "Cinnamon bark extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Black cohosh extract", mgAmount: 40, timingWindow: "with_meal" },
  { name: "Red clover extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Dong quai extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Black seed oil (Nigella sativa)", mgAmount: 500, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Sea buckthorn oil", mgAmount: 500, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Hemp seed oil", mgAmount: 1000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "MCT oil powder", mgAmount: 5000, fatSoluble: true, timingWindow: "with_meal" },
  { name: "Maitake mushroom extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Shiitake mushroom extract", mgAmount: 500, timingWindow: "with_meal" },
  { name: "Turkey tail mushroom extract", mgAmount: 500, timingWindow: "with_meal" },
];

export const INGREDIENT_BY_NAME = new Map(INGREDIENT_LIBRARY.map((i) => [i.name, i]));
